# Generated by Django 4.1.3 on 2023-01-18 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('satelite', models.CharField(max_length=50)),
                ('orbita', models.IntegerField()),
                ('incidente', models.IntegerField(blank=True, null=True)),
                ('comentario', models.TextField(max_length=250)),
                ('exitoso', models.BooleanField(blank=True, null=True)),
                ('a01ckb', models.BooleanField(blank=True, null=True)),
                ('a02ckb', models.BooleanField(blank=True, null=True)),
                ('a03ckb', models.BooleanField(blank=True, null=True)),
                ('a04ckb', models.BooleanField(blank=True, null=True)),
                ('a05ckb', models.BooleanField(blank=True, null=True)),
                ('a06ckb', models.BooleanField(blank=True, null=True)),
                ('a07ckb', models.BooleanField(blank=True, null=True)),
                ('a08ckb', models.BooleanField(blank=True, null=True)),
                ('a09ckb', models.BooleanField(blank=True, null=True)),
                ('a10ckb', models.BooleanField(blank=True, null=True)),
                ('a11ckb', models.BooleanField(blank=True, null=True)),
                ('a12ckb', models.BooleanField(blank=True, null=True)),
                ('a13ckb', models.BooleanField(blank=True, null=True)),
                ('a14ckb', models.BooleanField(blank=True, null=True)),
                ('a15ckb', models.BooleanField(blank=True, null=True)),
                ('a16ckb', models.BooleanField(blank=True, null=True)),
                ('a17ckb', models.BooleanField(blank=True, null=True)),
                ('a18ckb', models.BooleanField(blank=True, null=True)),
                ('a19ckb', models.BooleanField(blank=True, null=True)),
                ('a20ckb', models.BooleanField(blank=True, null=True)),
                ('a21ckb', models.BooleanField(blank=True, null=True)),
                ('a22ckb', models.BooleanField(blank=True, null=True)),
                ('a23ckb', models.BooleanField(blank=True, null=True)),
                ('a24ckb', models.BooleanField(blank=True, null=True)),
                ('a25ckb', models.BooleanField(blank=True, null=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
