# Generated by Django 4.1.3 on 2023-01-19 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appchecklists', '0002_alter_checklist_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='operador1',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
