# Generated by Django 4.1.3 on 2023-01-19 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appchecklists', '0003_checklist_operador1_alter_checklist_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
