# Generated by Django 4.1.3 on 2023-01-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appchecklists', '0004_alter_checklist_operador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='operador1',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='operador',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
