# Generated by Django 4.1.3 on 2023-01-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appchecklists', '0005_remove_checklist_operador1_alter_checklist_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='configuracion',
            field=models.IntegerField(default=False),
        ),
    ]
