# Generated by Django 4.1.3 on 2023-01-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appchecklists', '0006_checklist_configuracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='configuracion',
        ),
    ]
