# Generated by Django 4.1.3 on 2023-01-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appchecklists', '0007_remove_checklist_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='a26ckb',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
