from django import forms

class PasadaFormulario(forms.Form):
    satelite = forms.CharField(max_length=50,required=True)
    orbita = forms.IntegerField(required=True)
    incidente = forms.IntegerField(required=False)
    comentario = forms.CharField(max_length=250,required=False)
    exitoso = forms.BooleanField(required=False)
    a01ckb = forms.BooleanField(required=False)
    a02ckb = forms.BooleanField(required=False)
    a03ckb = forms.BooleanField(required=False)
    a04ckb = forms.BooleanField(required=False)
    a05ckb = forms.BooleanField(required=False)
    a06ckb = forms.BooleanField(required=False)
    a07ckb = forms.BooleanField(required=False)
    a08ckb = forms.BooleanField(required=False)
    a09ckb = forms.BooleanField(required=False)
    a10ckb = forms.BooleanField(required=False)
    a11ckb = forms.BooleanField(required=False)
    a12ckb = forms.BooleanField(required=False)
    a13ckb = forms.BooleanField(required=False)
    a14ckb = forms.BooleanField(required=False)
    a15ckb = forms.BooleanField(required=False)
    a16ckb = forms.BooleanField(required=False)
    a17ckb = forms.BooleanField(required=False)
    a18ckb = forms.BooleanField(required=False)
    a19ckb = forms.BooleanField(required=False)
    a20ckb = forms.BooleanField(required=False)
    a21ckb = forms.BooleanField(required=False)
    a22ckb = forms.BooleanField(required=False)
    a23ckb = forms.BooleanField(required=False)
    a24ckb = forms.BooleanField(required=False)
    a25ckb = forms.BooleanField(required=False)