from django import forms

class PasadaFormulario(forms.Form):
    satelite = forms.CharField(max_length=50)
    orbita = forms.IntegerField()
    incidente = forms.IntegerField()
    comentario = forms.CharField(max_length=250)
    exitoso = forms.BooleanField()
    _01ckb = forms.BooleanField()
    _02ckb = forms.BooleanField()
    _03ckb = forms.BooleanField()
    _04ckb = forms.BooleanField()
    _05ckb = forms.BooleanField()
    _06ckb = forms.BooleanField()
    _07ckb = forms.BooleanField()
    _08ckb = forms.BooleanField()
    _09ckb = forms.BooleanField()
    _10ckb = forms.BooleanField()
    _11ckb = forms.BooleanField()
    _12ckb = forms.BooleanField()
    _13ckb = forms.BooleanField()
    _14ckb = forms.BooleanField()
    _15ckb = forms.BooleanField()
    _16ckb = forms.BooleanField()
    _17ckb = forms.BooleanField()
    _18ckb = forms.BooleanField()
    _19ckb = forms.BooleanField()
    _20ckb = forms.BooleanField()
    _21ckb = forms.BooleanField()
    _22ckb = forms.BooleanField()
    _23ckb = forms.BooleanField()
    _24ckb = forms.BooleanField()
    _25ckb = forms.BooleanField()