from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Checklist(models.Model):
    id = models.AutoField(primary_key=True)
    fecha = models.DateTimeField(auto_now_add=True)
    satelite = models.CharField(max_length=50)
    orbita = models.IntegerField()
    operador = models.ForeignKey(User, on_delete=models.CASCADE,blank=True, null=True)
    operador1=models.CharField(max_length=50, default=False)
    incidente = models.IntegerField(blank=True, null=True)
    comentario = models.TextField(max_length=250)
    exitoso = models.BooleanField(blank=True, null=True)
    a01ckb = models.BooleanField(blank=True, null=True)
    a02ckb = models.BooleanField(blank=True, null=True)
    a03ckb = models.BooleanField(blank=True, null=True)
    a04ckb = models.BooleanField(blank=True, null=True)
    a05ckb = models.BooleanField(blank=True, null=True)
    a06ckb = models.BooleanField(blank=True, null=True)
    a07ckb = models.BooleanField(blank=True, null=True)
    a08ckb = models.BooleanField(blank=True, null=True)
    a09ckb = models.BooleanField(blank=True, null=True)
    a10ckb = models.BooleanField(blank=True, null=True)
    a11ckb = models.BooleanField(blank=True, null=True)
    a12ckb = models.BooleanField(blank=True, null=True)
    a13ckb = models.BooleanField(blank=True, null=True)
    a14ckb = models.BooleanField(blank=True, null=True)
    a15ckb = models.BooleanField(blank=True, null=True)
    a16ckb = models.BooleanField(blank=True, null=True)
    a17ckb = models.BooleanField(blank=True, null=True)
    a18ckb = models.BooleanField(blank=True, null=True)
    a19ckb = models.BooleanField(blank=True, null=True)
    a20ckb = models.BooleanField(blank=True, null=True)
    a21ckb = models.BooleanField(blank=True, null=True)
    a22ckb = models.BooleanField(blank=True, null=True)
    a23ckb = models.BooleanField(blank=True, null=True)
    a24ckb = models.BooleanField(blank=True, null=True)
    a25ckb = models.BooleanField(blank=True, null=True)