# Generated by Django 4.1.3 on 2023-01-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operador', models.CharField(default=False, max_length=50)),
                ('mensaje', models.TextField(null=True, verbose_name='Mensaje')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
